runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /static
  static_dir: static
  secure: always 
  
- url: /(.*\.(html|js|css|gif|png))
  static_files: static/\1
  upload: static/(.*\.(html|js|css|gif|png))
  secure: always  
  
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /.*
  script: main.app


libraries:
# Needed for SignedJwtAssertionCredentials
- name: pycrypto
  version: "2.6"
- name: ssl
  version: latest
